resources:
  - name: source_repo_pondpulse
    type: GitRepo
    configuration:
      gitProvider: git                     # <-- replace with your integration
      path: tpaz1/pondpulse  # <-- replace with your repository name
      branches:
        include: main
      buildOn:
        commit: true

  - name: artifact_repo_pondpulse
    type: Image
    configuration:
      registry: registry                               # <-- replace with your artifactory integration
      sourceRepository: docker             # <-- required if registry is Artifactory
      imageName: tompaz.jfrog.io/docker/pondpulse  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true

pipelines:
  - name: Docker_Build_Push_pondpulse
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: build_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: tompaz.jfrog.io/docker/pondpulse  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: source_repo_pondpulse
          integrations:
            - name: registry                            # <-- replace with your artifactory integration
        execution:
          onStart:
            - update_commit_status source_repo_pondpulse --message "starting...Building the container Image tompaz.jfrog.io/docker/pondpulse" --context "$step_name"
          onFailure:
            - update_commit_status source_repo_pondpulse --message "Failed! to build tompaz.jfrog.io/docker/pondpulse" --context "$step_name"
          onSuccess:
            - update_commit_status source_repo_pondpulse --message "Succeeded :-) build tompaz.jfrog.io/docker/pondpulse" --context "$step_name"

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: build_group
          targetRepository: docker
          integrations:
            - name: registry                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: artifact_repo_pondpulse
        execution:
          onFailure:
            - update_commit_status source_repo_pondpulse --message "Failed! couldnt upload image to tompaz.jfrog.io/docker/pondpulse" --context "$step_name"
          onSuccess:
            - update_commit_status source_repo_pondpulse --message "Succeeded :-) image tompaz.jfrog.io/docker/pondpulse succesfully pushed" --context "$step_name"
